"""Add invitation_code to orders

Revision ID: 239e2dc9ba5e
Revises: 98b4d364bd2e
Create Date: 2025-06-07 15:34:13.295635

"""
from typing import Sequence, Union

from sqlalchemy.sql import text
from alembic import op
import sqlalchemy as sa
import random
import string

# revision identifiers, used by Alembic.
revision: str = '239e2dc9ba5e'
down_revision: Union[str, None] = '98b4d364bd2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def generate_invitation_code():
    """生成随机邀请码"""
    return ''.join(random.choices(string.ascii_uppercase + string.digits, k=6))


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    conn = op.get_bind()

    # 初始化 invitation_code 字段
    users = conn.execute(text("SELECT id FROM users WHERE invitation_code IS NULL OR invitation_code = ''")).fetchall()
    for user in users:
        invitation_code = generate_invitation_code()
        conn.execute(
            text("UPDATE users SET invitation_code = :invitation_code WHERE id = :user_id"),
            {"invitation_code": invitation_code, "user_id": user.id}
        )


    # 添加唯一约束
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['invitation_code'])

    # 添加 invitation_code 字段到 orders 表
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invitation_code', sa.String(length=6), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('invitation_code')

    # ### end Alembic commands ###
