"""Add category_pinyin column to shops

Revision ID: bed23f19817a
Revises: e0f90e8d286e
Create Date: 2025-04-15 15:28:57.062514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bed23f19817a'
down_revision: Union[str, None] = 'e0f90e8d286e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_pinyin', sa.String(length=50), nullable=True))
        batch_op.drop_index('unique_name')
        batch_op.create_index(batch_op.f('ix_shops_category_pinyin'), ['category_pinyin'], unique=False)
        batch_op.create_index(batch_op.f('ix_shops_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shops_name'))
        batch_op.drop_index(batch_op.f('ix_shops_category_pinyin'))
        batch_op.create_index('unique_name', ['name'], unique=True)
        batch_op.drop_column('category_pinyin')

    # ### end Alembic commands ###
