"""Recreate missing migration

Revision ID: e0f90e8d286e
Revises: 080d6fed4883
Create Date: 2025-04-15 14:49:42.319719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0f90e8d286e'
down_revision: Union[str, None] = '080d6fed4883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_pinyin', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_shops_name_pinyin'), ['name_pinyin'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shops_name_pinyin'))
        batch_op.drop_column('name_pinyin')

    # ### end Alembic commands ###
